
DELETE FROM RTL_A.TRANSMITING_ADDRESS;
DELETE FROM RTL_A.TRANSMITING_CERTIFICATE;
DELETE FROM RTL_A.TRANSMITING_CONTACT;
DELETE FROM RTL_A.TRANSMITING_CUSTOMER;
DELETE FROM RTL_A.CUSTOMER_SYNCHRONIZE;
DELETE FROM RTL_A.CUSTOMER_ADDRESS;
DELETE FROM RTL_A.CUSTOMER_CERTIFICATE;
DELETE FROM RTL_A.CUSTOMER_CONTACT;
DELETE FROM RTL_A.CUSTOMER;

insert into RTL_A.CUSTOMER (TITLE, CODE)
values ('Ёлочкин', 'Палочкин');

insert into RTL_A.CUSTOMER (TITLE, CODE)
values ('Дремучий', 'Лес');

insert into RTL_A.CUSTOMER (TITLE, CODE)
values ('Гремучий', 'Ключ');

insert into RTL_A.CUSTOMER (TITLE, CODE)
values ('Гора', 'Белая');

insert into RTL_A.CUSTOMER (TITLE, CODE)
values ('Камень', 'Белый');

SELECT * FROM RTL_A.CUSTOMER;

INSERT INTO RTL_A.CUSTOMER_ADDRESS 
(CUSTOMER_ID,ADDRESS)
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Белый') AS a ,'Почта' AS b FROM dual UNION
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Белый'),'Отделение' FROM dual UNION
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Палочкин'),'хижина' FROM dual UNION
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Лес'),'третий куст от первого родника' FROM dual UNION
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Ключ'),'сухой горт' FROM dual 
;
SELECT * FROM RTL_A.CUSTOMER_ADDRESS;

INSERT INTO RTL_A.CUSTOMER_CERTIFICATE 
(CUSTOMER_ID,CERTIFICATE)
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Белый') AS a ,'паспорт РФ' AS b FROM dual UNION
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Палочкин'),'усы и хвост' FROM dual UNION
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Лес'),'нет документа' FROM dual UNION
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Ключ'),'водительские права' FROM dual 
;
SELECT * FROM RTL_A.CUSTOMER_CERTIFICATE;

INSERT INTO RTL_A.CUSTOMER_CONTACT 
(CUSTOMER_ID,CONTACT)
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Белый') AS a ,'8-902-272-65-35' AS b FROM dual UNION
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Палочкин'),'д. Левая Палка д5' FROM dual UNION
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Палочкин'),'д. Правая Палка ул Главная д1' FROM dual UNION
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Лес'),'на опушке леса кричать АУ' FROM dual UNION
    SELECT (SELECT ID FROM RTL_A.CUSTOMER WHERE CODE = 'Ключ'),'ulfnew@mail.ru' FROM dual 
;
SELECT * FROM RTL_A.CUSTOMER_CONTACT;

INSERT INTO RTL_A.CUSTOMER_SYNCHRONIZE 
(CUSTOMER_CODE,SYNCHRONIZE_STATUS)
    SELECT (SELECT CODE FROM RTL_A.CUSTOMER WHERE CODE = 'Палочкин') AS a ,'FOR_TRANSMIT' AS b FROM dual UNION
    SELECT (SELECT CODE FROM RTL_A.CUSTOMER WHERE CODE = 'Лес'),'NOT_FOUND' FROM dual UNION
    SELECT (SELECT CODE FROM RTL_A.CUSTOMER WHERE CODE = 'Ключ'),'FOR_TRANSMIT' FROM dual 
;
SELECT * FROM RTL_A.CUSTOMER_SYNCHRONIZE;

SELECT * FROM RTL_A.TRANSMITING_CUSTOMER;

DELETE FROM RTL_B.TRANSMITING_ADDRESS;
DELETE FROM RTL_B.TRANSMITING_CERTIFICATE;
DELETE FROM RTL_B.TRANSMITING_CONTACT;
DELETE FROM RTL_B.TRANSMITING_CUSTOMER;
DELETE FROM RTL_B.CUSTOMER_SYNCHRONIZE;
DELETE FROM RTL_B.CUSTOMER_ADDRESS;
DELETE FROM RTL_B.CUSTOMER_CERTIFICATE;
DELETE FROM RTL_B.CUSTOMER_CONTACT;
DELETE FROM RTL_B.CUSTOMER;

insert into RTL_B.CUSTOMER (TITLE, CODE)
values ('Печкин', 'Почтальон');

insert into RTL_B.CUSTOMER (TITLE, CODE)
values ('Лавочкин', 'Почтальён');

insert into RTL_B.CUSTOMER (TITLE, CODE)
values ('Ёлочкин', 'Палочкин');

insert into RTL_B.CUSTOMER (TITLE, CODE)
values ('Дремучий', 'Лес');

insert into RTL_B.CUSTOMER (TITLE, CODE)
values ('Гремучий', 'Ключ');

SELECT * FROM RTL_B.CUSTOMER;

INSERT INTO RTL_B.CUSTOMER_ADDRESS 
(CUSTOMER_ID,ADDRESS)
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Почтальон') AS a ,'Почта' AS b FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Почтальон'),'Отделение' FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Почтальён'),'печка' FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Палочкин'),'хижина' FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Лес'),'третий куст от первого родника' FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Ключ'),'сухой горт' FROM dual 
;
SELECT * FROM RTL_B.CUSTOMER_ADDRESS;

INSERT INTO RTL_B.CUSTOMER_CERTIFICATE 
(CUSTOMER_ID,CERTIFICATE)
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Почтальон') AS a ,'паспорт РФ' AS b FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Почтальён'),'пачпорт' FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Почтальён'),'поспорт' FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Палочкин'),'усы и хвост' FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Лес'),'нет документа' FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Ключ'),'водительские права' FROM dual 
;
SELECT * FROM RTL_B.CUSTOMER_CERTIFICATE;

INSERT INTO RTL_B.CUSTOMER_CONTACT 
(CUSTOMER_ID,CONTACT)
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Почтальон') AS a ,'8-902-272-65-35' AS b FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Почтальён'),'улица нагорная дом 5' FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Палочкин'),'д. Левая Палка д5' FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Палочкин'),'д. Правая Палка ул Главная д1' FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Лес'),'на опушке леса кричать АУ' FROM dual UNION
    SELECT (SELECT ID FROM RTL_B.CUSTOMER WHERE CODE = 'Ключ'),'ulfnew@mail.ru' FROM dual 
;
SELECT * FROM RTL_B.CUSTOMER_CONTACT;

INSERT INTO RTL_B.CUSTOMER_SYNCHRONIZE 
(CUSTOMER_CODE,SYNCHRONIZE_STATUS)
    SELECT (SELECT CODE FROM RTL_B.CUSTOMER WHERE CODE = 'Почтальон') AS a ,'FOR_TRANSMIT' AS b FROM dual UNION
    SELECT (SELECT CODE FROM RTL_B.CUSTOMER WHERE CODE = 'Почтальён'),'INITIALIZE' FROM dual UNION
    SELECT (SELECT CODE FROM RTL_B.CUSTOMER WHERE CODE = 'Лес'),'NOT_FOUND' FROM dual UNION
    SELECT (SELECT CODE FROM RTL_B.CUSTOMER WHERE CODE = 'Ключ'),'FOR_TRANSMIT' FROM dual 
;
SELECT * FROM RTL_B.CUSTOMER_SYNCHRONIZE;

SELECT * FROM RTL_B.TRANSMITING_CUSTOMER;
